---
- hosts: all
  gather_facts: no
  tasks:
   - name: Update all apt packages to latest
     apt: upgrade=dist

   - name: Add nginx to apt-rep
     apt_repository: repo='ppa:nginx/stable' state='present'
     register: test1

   - name: Install nginx
     apt: pkg=nginx state=present update_cache=true
     when: test1 is success
     notify: Start nginx
  handlers:
   - name: Start nginx
     service: name=nginx state=started
